version: '2'
services:
  nginx:
    image: mondayfactory/nginx-php71
    ports:
      - 63001:80
    volumes:
      - .:/data:delegated
    environment:
      ENVIRONMENT: local
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS:
      MYSQL_DB_NAME: datagrid_sandbox

  mysql:
    image: mysql:5.7
    ports:
      - 63002:3306
    volumes:
      - ./_data/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
